version: '2'
services:
    examen2-app:
        image: examen2
        external_links:
            - examen2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/examen2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    examen2-mysql:
        extends:
            file: mysql.yml
            service: examen2-mysql
